# Generated by Django 5.1.4 on 2025-01-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='personal_salud',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='historia_clinica',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
