# Generated by Django 5.1.4 on 2025-01-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_entradaevolucion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnexoHistoriaClinica',
        ),
    ]
