# Generated by Django 5.1.4 on 2025-01-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_delete_anexohistoriaclinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaevolucion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='entradas_evolucion/'),
        ),
    ]
