# Generated by Django 5.1.4 on 2025-01-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_perfil_link_web_alter_perfil_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Imagen de Perfil'),
        ),
    ]
