# Generated by Django 5.1.4 on 2025-01-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_alter_perfil_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='descripcion',
        ),
    ]
