# Generated by Django 5.1.4 on 2025-01-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('Medicina General', 'Medicina General'), ('Enfermería', 'Enfermería'), ('Pediatría', 'Pediatría'), ('Cardiología', 'Cardiología'), ('Traumatología', 'Traumatología'), ('Anestesiología', 'Anestesiología')], max_length=50, null=True, verbose_name='Especialidad'),
        ),
    ]
