# Generated by Django 5.1.4 on 2025-01-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apellido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nro_matricula_profesional',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nro de Matrícula Profesional'),
        ),
    ]
