# Generated by Django 5.1.4 on 2025-01-06 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0003_auto_20170827_1345'),
        ('usuarios', '0004_alter_customuser_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='avatar.avatar'),
        ),
    ]
