# Generated by Django 5.1.4 on 2025-01-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_customuser_avatar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar_image',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('Medicina General', 'Medicina General'), ('Enfermería', 'Enfermería'), ('Pediatría', 'Pediatría'), ('Cardiología', 'Cardiología'), ('Traumatología', 'Traumatología'), ('Anestesiología', 'Anestesiología'), ('Terapia Intensiva', 'Terapia Intensiva')], max_length=50, null=True, verbose_name='Especialidad'),
        ),
    ]
