# Generated by Django 5.1.4 on 2025-01-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_customuser_avatar_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('Clínica', 'Clínica'), ('Enfermería', 'Enfermería'), ('Pediatría', 'Pediatría'), ('Cardiología', 'Cardiología'), ('Traumatología', 'Traumatología'), ('Anestesiología', 'Anestesiología'), ('Terapia Intensiva', 'Terapia Intensiva')], max_length=50, null=True, verbose_name='Especialidad'),
        ),
    ]
