# Generated by Django 5.1.4 on 2025-01-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_customuser_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('Admision', 'Admision'), ('Clínica', 'Clínica'), ('Enfermería', 'Enfermería'), ('Pediatría', 'Pediatría'), ('Cardiología', 'Cardiología'), ('Traumatología', 'Traumatología'), ('Anestesiología', 'Anestesiología'), ('Terapia Intensiva', 'Terapia Intensiva'), ('Cirujia General', 'Cirugia General'), ('Imagenología', 'Imagenología')], max_length=50, null=True, verbose_name='Especialidad'),
        ),
    ]
